### ISSUE TITLE
`meteoplot` function not working as intended with SpatialGridMeteorology class objects

### ISSUE THREAD

**Issue by MalditoBarbudo** [miquelcaceres/meteoland#4]
When using `meteoplot` function with an SpatialGridMeteorology the index argument, which in the help indicates that is the cell index, in reality indexes by date, making impossible to plot cells with index higher than the number of dates in the object. Also I'm not sure that with this error the function is plotting the data we want.

Function code related to this issue:

> vec = numeric(length(dates))
    for(i in 1:length(dates)) {
      idate = which(object@dates == dates[i])
      if(!(var %in% c("MaxMinTemperatureDiff","MaxMeanTemperatureDiff", "MinMeanTemperatureDiff"))) {
        vec[i] = object@data[[index]][idate,var]
      } else if(var=="MaxMinTemperatureDiff") {
        vec[i] = object@data[[index]][idate,"MaxTemperature"]-object@data[[index]][idate,"MinTemperature"]
      } else if(var=="MaxMeanTemperatureDiff") {
        vec[i] = object@data[[index]][idate,"MaxTemperature"]-object@data[[index]][idate,"MeanTemperature"]
      } else if(var=="MinMeanTemperatureDiff") {
        vec[i] = object@data[[index]][idate,"MinTemperature"]-object@data[[index]][idate,"MeanTemperature"]
      } 
    }

**Comment by miquelcaceres** [comment]
I decided to restrict meteoplot to SpatialPointMeteorology objects. To study the series from grids the user should first use function extractgridpoints.
